### ISSUE TITLE
What is the meaning of Features and Labels?

### ISSUE THREAD

**Issue by gyp04225** [liuruoze/mini-AlphaStar#23] opened 2022-05-12 06:02 UTC
Hello, My name is Chan Uk Lee. I am a Korea Maritime and Ocean University Master course student.

I am very interested in your artificial intelligence Mini-Alphastar.

but it is very difficult for me to understand.

So I have a question.

Transform replay data python file get Features and Label.

What is the meaning of Features and Labels? and How can i get Features and Labels?

Last, How are Features and Labels used in supervised learning?
![캡처](https://user-images.githubusercontent.com/84261503/168002534-226be98c-5f6f-4b58-9350-96e082a795ef.JPG)

**Comment by liuruoze** [comment] 2022-06-16 02:55
Hi, you can understand what it means through readings of the related codes (I don't know how to explain it well).

**Comment by liuruoze** [comment] 2022-06-21 11:05
Hi, I will close this issue if you don't have new questions. You can always re-open it if you think the problem is not resolved.

**Closed as completed by liuruoze** 2022-06-21 11:05 UTC
