### ISSUE TITLE
Unable to Process Replays?

### ISSUE THREAD

**Issue by windowshopr** [liuruoze/mini-AlphaStar#21] opened 2022-03-26 02:03 UTC
Just discovered this repo, and I'm extremely interested in getting started with SC2 RL, but I'm quickly finding that most of these repo's aren't maintained anymore/they're from versions of the game LONG ago, so I'm hoping to get some insight.

Now, using this repo, and running Windows 10, Python 3.10, and SC2 version 5.0.9, my `run.py` looks like this:

![image](https://user-images.githubusercontent.com/40477419/160220289-4da07fea-f38f-4123-8f37-7779e5ac3bcf.png)

Pretty standard, I'm just trying to run the `transform_replay_data` part. I've also updated the path where the replays are read from in the `transform_replay_data.py` file to `flags.DEFINE_string("no_server_replay_path", "C:\\Program Files (x86)\\StarCraft II\\Replays\\", "path of replay data")`. (Double slashes re: Windows).

I run the script, and it looks like it's trying to run, but essentially, it just flies through all the replay files I have in that directory, but it doesn't actually "do" anything, it just looks like this at the end:

![image](https://user-images.githubusercontent.com/40477419/160220372-012001c9-e396-4402-b7ef-34af49f26fda.png)

I don't see any errors or anything to suggest what it might be, but my guess is it has something to do with the version of replays vs the version of my current game. I've seen in previous posts that you need to actually open the replays in order to download the older versions of the games, which I have done already, and I can see the added version in my `Versions` directory, but still no dice.

The maps I've downloaded include:

![image](https://user-images.githubusercontent.com/40477419/160220447-9f920f87-31ef-4242-a81d-aa18efd7ead8.png)

....in case that's relevant. I've also read online that there's a difference between local maps files, and battle.net map files as the latter is played online, and uses a `.s2ma` extension. In order to download the maps for each replay, the best advice I saw was to enter `-PrePopulateCache` as an additional command argument in the `Battle.net > Game Options` settings which downloads those cache files for you, so I've done that as well.

Any ideas on what a guy can try to troubleshoot this? Any help would be greatly appreciated as I'd love to explore this space using the current versions of everything! lol Thanks!

**Comment by liuruoze** [comment] 2022-03-29 00:41
Hi, sorry for the late reply. I have read your description completely. First of all thanks for these detailed descriptions. I have understood your question. This problem is really strange. It seems that the script just skips each replay without opening them.

On normal circumstances, PySC2 will open the SC2 program, and then run the replay (the program will process the replay information in the background and store them as tensor), and the external performance is like a human watching these replays. But this didn't happen. I have the following suggestions:

1. Turn on the debug option. On line 49 of "transform_replay_data", change "debug=False" to "debug=True", which will give more debug information to indicate where the problem might be.
2. If there is no more useful information above, could the problem be these replays? You can use our replay generated on Simple64. These replays have been tested and can indeed be processed and used for training.
3. Another possibility is that the version of your replay is too new? I suspect that you may be using a version of replay above 4.10.1 (eg the 5.0 series). These replays are available, but require modification of the PySC2 source code. The specific modification location is a variable called "VERSIONS" in "run_configs/lib.py" in the PySC2 source code. Some information about the corresponding SC2 version needs to be added to this dict. These values ​​require access to a Blizzard repository (https://github.com/Blizzard/s2client-proto/blob/master/buildinfo/versions.json) to obtain.

These are some of my suggestions. If it has not been resolved, we can continue to discuss it. Hope to have better progress.

**Comment by windowshopr** [comment] 2022-03-29 01:31
Not a problem, thanks for the reply!

Well, using the `debug=True` suggestion, I saw that the program was having trouble "finding" the directory/replay file for some reason, and it might have been because of my double slashing, so I changed this path:

`"C:\\Program Files (x86)\\StarCraft II\\Replays\\"`

to

`"C:/Users/chalu/OneDrive/Desktop/Python_Scripts/mini-AlphaStar-main/replays/"`

(ensuring the last slash is in the filepath as well), and it seemed to work without any debug errors, but now I have a new problem.

The output of my run now looks like this:

```
replay_info map_name: "Acropolis LE"
local_map_path: "AcropolisLE.SC2Map"
player_info {
  player_info {
    player_id: 1
    race_requested: Terran
    race_actual: Terran
  }
  player_result {
    player_id: 1
    result: Victory
  }
  player_apm: 3678
}
player_info {
  player_info {
    player_id: 2
    race_requested: Zerg
    race_actual: Zerg
  }
  player_result {
    player_id: 2
    result: Defeat
  }
  player_apm: 422
}
game_duration_loops: 8296
game_duration_seconds: 370.38299560546875
game_version: "5.0.9.87702"
data_build: 87702
base_build: 87702
data_version: "F799E093428D419FD634CCE9B925218C"

type(replay_info) <class 's2clientprotocol.sc2api_pb2.ResponseReplayInfo'>
replay_info.player_info： [player_info {
  player_id: 1
  race_requested: Terran
  race_actual: Terran
}
player_result {
  player_id: 1
  result: Victory
}
player_apm: 3678
, player_info {
  player_id: 2
  race_requested: Zerg
  race_actual: Zerg
}
player_result {
  player_id: 2
  result: Defeat
}
player_apm: 422
]
info： player_info {
  player_id: 1
  race_requested: Terran
  race_actual: Terran
}
player_result {
  player_id: 1
  result: Victory
}
player_apm: 3678

player_info player_id: 1
race_requested: Terran
race_actual: Terran

info： player_info {
  player_id: 2
  race_requested: Zerg
  race_actual: Zerg
}
player_result {
  player_id: 2
  result: Defeat
}
player_apm: 422

player_info player_id: 2
race_requested: Zerg
race_actual: Zerg

observe_id_list []
observe_result_list []
win_observe_id 0
no win_observe_id found! continue
replay_path: C:/Users/chalu/OneDrive/Desktop/Python_Scripts/mini-AlphaStar-main/replays/Catalyst LE (2).SC2Replay
replay_path: C:/Users/chalu/OneDrive/Desktop/Python_Scripts/mini-AlphaStar-main/replays/Catalyst LE.SC2Replay
replay_path: C:/Users/chalu/OneDrive/Desktop/Python_Scripts/mini-AlphaStar-main/replays/Simple Test Map 64x64 (2).SC2Replay
replay_path: C:/Users/chalu/OneDrive/Desktop/Python_Scripts/mini-AlphaStar-main/replays/Simple Test Map 64x64 (3).SC2Replay
replay_path: C:/Users/chalu/OneDrive/Desktop/Python_Scripts/mini-AlphaStar-main/replays/Simple Test Map 64x64 (4).SC2Replay
replay_path: C:/Users/chalu/OneDrive/Desktop/Python_Scripts/mini-AlphaStar-main/replays/Simple Test Map 64x64 (5).SC2Replay
replay_path: C:/Users/chalu/OneDrive/Desktop/Python_Scripts/mini-AlphaStar-main/replays/Simple Test Map 64x64.SC2Replay
100%|███████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 227.56it/s]
end
replay_length_list: []
noop_length_list: []
run over
```

So I see there is a `no win_observe_id found! continue` line in there, which might hint at something? These 9 replays are from my current version of 5.0.9. I also tested on the old replay files from the Season2017 folders, but same issue. I would assume those replays are from older versions of the game, but thought I'd test them on both to see.

I did come across the `versions.json` file in PySC2 as well during my travels in this space haha, and after running this script, I noticed the hash value for my current game version, so my next step is to modify that `versions.json` file to include my latest game version, and retry some stuff. I will report back if I have anything changed.

**Comment by windowshopr** [comment] 2022-03-29 02:44
Hmm, still no dice. And I see now that just adding the game version and hash code isn't enough, we need to get a replay hash code, and some other one as well to add to that json file, which it doesn't look like is posted. Too bad.

So, to recreate my issue, I re-installed/re-downloaded a fresh mini-AlphaStar and installed dependencies.

I then ran:

`python -m scripts.download_replay.third.download_replays --key xxxxxxxxxxxxxxxxxxx --secret xxxxxxxxxxxxx --version 4.7.1 --filter_version delete`

... and downloaded the first two replay .zip files, the first one is quite small, so I will test using that.

I unzipped the replay files manually to a `replays` folder in the main mini-AlphaStar directory, shown here:

![image](https://user-images.githubusercontent.com/40477419/160519777-58294e6b-f994-45a8-9d47-e3f0bd605f24.png)

So at this state, the replays are of version 4.7.1, and my current game version is 5.0.9.

I manually double clicked the first 2 replay files to make sure any map files/resources/old versions of the game were downloaded ahead of time. Would suck to think I have to do this for every replay file, but we'll see.

I then make sure that I've updated this line in the `transform_replay_data.py` file to show the correct directory of the replay files:

`flags.DEFINE_string("no_server_replay_path", "C:/Users/chalu/OneDrive/Desktop/Python_Scripts/mini-AlphaStar-main/replays/", "path of replay data")`

and make sure `debug=True`, then run `python run.py`. I'm then greeted with these error message(s):

```
Traceback (most recent call last):
  File "C:\Users\chalu\OneDrive\Desktop\Python_Scripts\mini-AlphaStar-main\alphastarmini\core\sl\transform_replay_data.py", line 398, in test
    replay_info = controller.replay_info(replay_data)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\lib\remote_controller.py", line 74, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\lib\remote_controller.py", line 65, in check_error
    raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details), res)
pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseReplayInfo.Error.ParsingError: 'Possible corruption - Failed to open the map archive: C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\01\85\0185d86c0b4648e077dba1081af147ac6d50b1db11ce41012ee3fb32f5a8cb35.s2ma'
```

AHA! So this is where the .s2ma extension for multiplayer online maps comes into play. Also, that's NOT my main cache folder where the default install of SC2 is on my machine. My default install location is actually `C:\Program Files (x86)\StarCraft II` where there is its own battle.net folder and a cache folder within it, so it appears there are 2 cache folders for some reason.

When I look in the one that's giving the error (C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\), it's right, there isn't a `\01\85\0185d86c0b4648e077dba1081af147ac6d50b1db11ce41012ee3fb32f5a8cb35.s2ma` structure in there, but there IS in the main install directory's cache file!

So the question at this point is, how can we modify pysc2 to NOT look in `C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\` but rather `C:\Program Files (x86)\StarCraft II\Battle.net\Cache`??????

So what I've done now is, copy the correct folder from the good directory, to the bad directory to ensure the map file is in fact in there, and run `python run.py` again. I now see this:

```
----------------------- Replay info ------------------------
replay_info map_name: "Fracture LE"
player_info {
  player_info {
    player_id: 1
    race_requested: Terran
    race_actual: Terran
  }
  player_result {
    player_id: 1
    result: Defeat
  }
  player_mmr: 4705
  player_apm: 170
}
player_info {
  player_info {
    player_id: 2
    race_requested: Protoss
    race_actual: Protoss
  }
  player_result {
    player_id: 2
    result: Victory
  }
  player_mmr: 4624
  player_apm: 354
}
game_duration_loops: 1642
game_duration_seconds: 73.30868530273438
game_version: "4.7.1.70326"
data_build: 70326
base_build: 70154
data_version: "94596A85191583AD2EBFAE28C5D532DB"

------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\chalu\OneDrive\Desktop\Python_Scripts\mini-AlphaStar-main\alphastarmini\core\sl\transform_replay_data.py", line 446, in test
    controller.start_replay(start_replay)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\lib\remote_controller.py", line 99, in _valid_status
    return func(self, *args, **kwargs)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\lib\remote_controller.py", line 74, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\lib\remote_controller.py", line 65, in check_error
    raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details), res)
pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseStartReplay.Error.LaunchError: 'The launch of this game makes reference to mod or map dependencies which are no longer available.'
```

phewf, ok, so then I find [this article](https://github.com/deepmind/pysc2/issues/94) that says to try and copy over the map files to the bad cache area (when you go back a directory, there's a StarCraft2 folder with a maps folder in it), so I just copied all of my map files from my main install/good directory's maps folder over to there and tried again. Same error as above.

SO THEN, I ran into another article, which I can't seem to find in my history to reference anymore, that you can re-run the game from the battle.net app, and add `-PrePopulateCache` as an additional command line argument to try and re-download any missing resources. So I copied all of the replay files from the mini-AlphaStar folder to the main install directory's Replays folder to make sure they were in there, and did just that. The cache gets "populated" but when I run `python run.py` again, I get the same error.

I am officially out of ideas to try lol maybe someone who reads this can help out, but that's as far as I can get with it for tonight. Sorry for the long read.

**Comment by liuruoze** [comment] 2022-04-01 08:38
Hi, due to that I'm somewhat busy these days, sorry for replying late. First of all thanks for the more details. This description does seem very long. But I have read all your descriptions completely (however, some are so complicated that I may not understand them very clearly). 

I noticed that the replay you used was about Zerg against Terran. Unfortunately, mini-AlphaStar is specifically focused on Protoss training. Generally speaking, we give it a replay of Protoss vs. Protoss or Protoss vs. other races. The mAS can support other races but requires some tweaking to the code, and I haven't tested it yet. Support for other races will be one of the features we support in the future.

As for other questions about maps and versions, it will be much smaller. If you agree with Protoss as the main training race, you can test it first with the replay we provide. There should be no issues with these replay versions and maps.

Regarding the information that our current mini-AlphaStar version is particularly suitable for Protoss training, we are sorry that we did not clearly explain it in the readme. We will supplement this information.

**Comment by liuruoze** [comment] 2022-06-16 02:52
Hi, I will close this issue if you don't have new questions. You can always re-open it if you think the problem is not resolved.

**Closed as completed by liuruoze** 2022-06-16 02:52 UTC

**Comment by softclone** [comment] 2023-01-03 23:26
I am also getting "no win_observe_id found" when trying to process replays. using the provided 3.16.1 version simple64 replays.

(th_1_5) D:\code\mini-AlphaStar>python run.py
pygame 2.1.2 (SDL 2.0.18, Python 3.7.15)
Hello from the pygame community. https://www.pygame.org/contribute.html
run init
REPLAY_PATH: D:/code/mini-AlphaStar/data/Replays/filtered_replays_1/
length of replay_files: 1
  0%|                                                                                                                                                | 0/1 [00:00<?, ?it/s]replay_path: D:/code/mini-AlphaStar/data/Replays/filtered_replays_1/Simple64_2021-12-28-07-47-43.SC2Replay
replay_info map_name: "Simple Test Map 64x64"
local_map_path: "Melee/Simple64.SC2Map"
player_info {
  player_info {
    player_id: 1
    race_requested: Protoss
    race_actual: Protoss
  }
  player_result {
    player_id: 1
    result: Victory
  }
  player_apm: 16
}
player_info {
  player_info {
    player_id: 2
    race_requested: Terran
    race_actual: Terran
  }
  player_result {
    player_id: 2
    result: Defeat
  }
  player_apm: 29
}
game_duration_loops: 8766
game_duration_seconds: 391.3666076660156
game_version: "3.16.1.55958"
data_build: 55958
base_build: 55958
data_version: "5BD7C31B44525DAB46E64C4602A81DC2"

type(replay_info) <class 's2clientprotocol.sc2api_pb2.ResponseReplayInfo'>
replay_info.player_info: [player_info {
  player_id: 1
  race_requested: Protoss
  race_actual: Protoss
}
player_result {
  player_id: 1
  result: Victory
}
player_apm: 16
, player_info {
  player_id: 2
  race_requested: Terran
  race_actual: Terran
}
player_result {
  player_id: 2
  result: Defeat
}
player_apm: 29
]
info: player_info {
  player_id: 1
  race_requested: Protoss
  race_actual: Protoss
}
player_result {
  player_id: 1
  result: Victory
}
player_apm: 16

player_info player_id: 1
race_requested: Protoss
race_actual: Protoss

info: player_info {
  player_id: 2
  race_requested: Terran
  race_actual: Terran
}
player_result {
  player_id: 2
  result: Defeat
}
player_apm: 29

player_info player_id: 2
race_requested: Terran
race_actual: Terran

observe_id_list [1]
observe_result_list [1]
win_observe_id 0
no win_observe_id found! continue
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 83.33it/s]
end
replay_length_list: []
noop_length_list: []
run over

**Comment by softclone** [comment] 2023-01-03 23:59
ok got this working by downgrading s2clientprotocol
